### ISSUE TITLE
Suggestion add

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#178] opened 2021-05-14 05:14 UTC
When you buy a sub for chat, the farming coefficient becomes 1.2 at 1 and 2 levels, and at 3 levels it becomes 2. Can you add the function to farm first of all on channels with a purchased / donated sub?

**Comment by RakSrinaNa** [comment] 2021-05-14 05:39
Duplicate of #166

**Closed** 2021-05-14 05:44 UTC
Labels: enhancement
