### ISSUE TITLE
Issue trying to deploy to Heroku

### ISSUE THREAD

**Issue by Microck** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#449] opened 2022-03-10 10:09 UTC
Ive seen the #130 thread and tried the "solution" in one of the comments, but im still having issues.

Normal deploy:
![image](https://user-images.githubusercontent.com/45483921/157638796-8746080f-dd05-4f9b-964d-56b5c5a58726.png)

leognutzmann's solution deploy:
![image](https://user-images.githubusercontent.com/45483921/157639290-f255f80a-a14b-45d2-9050-dfb46a0a5481.png)

I have 0 knowledge about coding, so it might be a dumb error. I uploaded the repo with the cookies folder, a Procfile and a runtime.txt file > 
![image](https://user-images.githubusercontent.com/45483921/157639613-d7903744-4bec-40ce-a756-8491d2628a4a.png)
![image](https://user-images.githubusercontent.com/45483921/157639659-a6781178-c25d-4463-b005-94ecc74fc775.png)

**Comment by Tkd-Alex** [comment] 2022-03-10 10:39
Duplicate of #447 
I'll answer both on that issue

**Closed by Tkd-Alex** 2022-03-10 10:39 UTC
Labels: bug

**Comment by Microck** [comment] 2022-03-10 10:42
Aight, thank you
