### ISSUE TITLE
followers not found?

### ISSUE THREAD

**Issue by acowsays** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#284] opened 2021-09-28 22:44 UTC
**Describe the bug**
followers not found?

**To Reproduce**

2. Click on 'run.py'

**Expected behavior**
28/09/21 18:41:42 - INFO - TwitchChannelPointsMiner.TwitchChannelPointsMiner - [run]: Start session: '45c3222c-d0c2-4e7b-94fe-35ab7068e9e5'
28/09/21 18:41:42 - DEBUG - urllib3.connectionpool - [_new_conn]: Starting new HTTPS connection (1): api.twitch.tv:443
28/09/21 18:41:43 - DEBUG - urllib3.connectionpool - [_make_request]: https://api.twitch.tv:443 "GET /helix/users/follows?from_id=159918761&first=100 HTTP/1.1" 404 47
28/09/21 18:41:43 - DEBUG - TwitchChannelPointsMiner.classes.Twitch - [__do_helix_request]: Query: /users/follows?from_id=159918761&first=100, Status code: 404, Content: {'error': 'Not Found', 'status': 404, 'message': ''}

**Desktop (please complete the following information):**
 - OS: win 10
 - Python version [latest]

**Comment by LC-BWF** [comment] 2021-09-29 00:01
Same issue for me started happening today.
OS: Win Server 2022

**Comment by KEKLBruh** [comment] 2021-09-29 01:02
same prob on my Pi

**Comment by VitaliShilov** [comment] 2021-09-29 06:24
same win7

**Comment by RakSrinaNa** [comment] 2021-09-29 06:35
Duplicate of #281

**Comment by Tkd-Alex** [comment] 2021-09-29 14:02
Someone can test this?
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288

**Closed** 2021-10-01 08:54 UTC
Labels: bug
