### ISSUE TITLE
Got this error randomly after running the script

### ISSUE THREAD

**Issue by ItsCerv** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#547] opened 2022-07-10 19:06 UTC
![image](https://user-images.githubusercontent.com/108262957/178158560-3d4f525c-c790-4bf9-ab7b-f38697df6cc0.png)

How do i fix this?

**Comment by egorcreep** [comment] 2022-07-11 01:21
![image](https://user-images.githubusercontent.com/58714525/178171649-cef44fce-33d4-4beb-8c75-4190e3b3d634.png)
same

**Comment by Tkd-Alex** [comment] 2022-07-11 09:11
Analytics corrupted.
Please remove the corrupted file or the entire folder

Duplicate of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/441 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/398 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/358 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/381 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/187 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/266

**Closed by Tkd-Alex** 2022-07-11 09:11 UTC
Labels: duplicate
