### ISSUE TITLE
doesnt see streamers and show error

### ISSUE THREAD

**Issue by sad1k** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#290] opened 2021-09-29 15:12 UTC
**Describe the bug**
doesnt see streamers and shows this " Traceback (most recent call last):
  File "E:\twitch mine\Twitch-Channel-Points-Miner-v2-master\run.py", line 65, in <module>
    twitch_miner.mine(
  File "E:\twitch mine\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "E:\twitch mine\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run
    user_id=self.twitch.twitch_login.get_user_id(),
  File "E:\twitch mine\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id
    return int(self.get_cookie_value("persistent").split("%")[0])
AttributeError: 'NoneType' object has no attribute 'split' "

**To Reproduce**
1. Open script

**Expected behavior**
Today me got some errors, but it not break script
Today i cant start script after restart pc 

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version 3.9

**Additional context**
![Screenshot_31](https://user-images.githubusercontent.com/91619133/135297108-89c93fde-2cdd-442a-9f8b-6cc1b2e2fb1f.png)

**Comment by RakSrinaNa** [comment] 2021-09-29 15:15
Duplicate of #281

**Closed** 2021-09-29 16:11 UTC
Labels: bug
