### ISSUE TITLE
Duplicate Lines after adding analytics.

### ISSUE THREAD

**Issue by krystlerc** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#363] opened 2021-12-21 04:10 UTC
**Describe the bug**
I added analytics to the run.py. Added it right after the comments after the streamersettings.

```
twitch_miner = TwitchChannelPointsMiner("*********")
twitch_miner.analytics(host="0.0.0.0", port=5000, refresh=5)   # Analytics web-server
twitch_miner.mine(followers=True, blacklist=["user1", "user2"])
```
Then commented out the previous settings for miner which is provided by the example.py.

**To Reproduce**
1. Add analytics to the run.py after the comments after the streamersettings.
2. commented out the previous miner settings which is provided by example.py
3. run the run.py
4. See duplicate lines which is probably a bug or does the analytics cause it to duplicate??

**Expected behavior**
I expected a non duplicate lines in command line.

**Desktop (please complete the following information):**
 - OS: windows 10 64x
 - Python version 3.10

**Additional context**
```
21/12/21 11:55:00 - ERROR - [__init__]: Unable to detect if you have the latest version of this script
21/12/21 11:55:00 - ERROR - [__init__]: Unable to detect if you have the latest version of this script
21/12/21 11:55:00 - ERROR - [__init__]: Unable to detect if you have the latest version of this script
21/12/21 11:55:00 - INFO - [run]: 🌐  Analytics running on http://0.0.0.0:5000/
21/12/21 11:55:00 - INFO - [run]: 💣  Start session: '7c0518d6-be6f-4719-b5d4-e1d9cb96d280'
21/12/21 11:55:00 - INFO - [run]:   Analytics running on http://0.0.0.0:5000/
21/12/21 11:55:00 - INFO - [run]:   Start session: '7c0518d6-be6f-4719-b5d4-e1d9cb96d280'
21/12/21 11:55:01 - INFO - [run]: 📋  Load 12 followers from your profile!
21/12/21 11:55:01 - INFO - [run]:   Load 12 followers from your profile!
21/12/21 11:55:01 - INFO - [run]: 🤓  Loading data for 12 streamers. Please wait...
21/12/21 11:55:01 - INFO - [run]:   Loading data for 12 streamers. Please wait...
21/12/21 11:55:15 - INFO - [run]: 💬  Join IRC Chat: shroud
21/12/21 11:55:15 - INFO - [run]:   Join IRC Chat: shroud
21/12/21 11:55:15 - INFO - [set_online]: 🥳  Streamer(username=shroud, channel_id=37402112, channel_points=3.84k) is Online!
21/12/21 11:55:15 - INFO - [set_online]:   Streamer(username=shroud, channel_id=37402112, channel_points=3.84k) is Online!
```

**Comment by Tkd-Alex** [comment] 2021-12-21 10:42
Probably It's a duplicate of #175

**Comment by krystlerc** [comment] 2021-12-21 12:33
oh i see. i fixed it now. thanks!

**Closed** 2021-12-21 12:34 UTC
Labels: bug
