### ISSUE TITLE
Exception raised for topic: community-points-user-v1 and message error when certain streamer on my list started streaming

### ISSUE THREAD

**Issue by haleypadawan** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#398] opened 2022-01-18 09:33 UTC
**Describe the bug**
One of the streamer I have on my list keeps showing this error when they are streaming
`18/01 17:22:09 - Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2022-01-18T09:22:10.988788205Z', 'channel_id': '254756234', 'point_gain': {'user_id': '5842591', 'channel_id': '254756234', 'total_points': 10, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': []}, 'balance': {'user_id': '5842591', 'channel_id': '254756234', 'balance': 568080}}}
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\New Folder\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 181, in on_message
    ws.streamers[streamer_index].persistent_series(
  File "C:\Users\admin\Desktop\New Folder\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\entities\Streamer.py", line 219, in persistent_series
    self.__save_json("series", event_type=event_type)
  File "C:\Users\admin\Desktop\New Folder\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\entities\Streamer.py", line 234, in __save_json
    json_data = json.load(open(fname, "r")) if os.path.isfile(fname) else {}
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12140 column 24 (char 250178)`

**To Reproduce**
1. Wait for the streamer to stream

**Expected behavior**
Streamer name, points and points added should be shown normally

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.6

**Comment by Tkd-Alex** [comment] 2022-01-18 10:46
Duplicate of #358 #381 #187 #266

**Closed by Tkd-Alex** 2022-01-18 10:46 UTC
Labels: duplicate
