### ISSUE TITLE
Staying connected in an IRC channel (offline)

### ISSUE THREAD

**Issue by Yishaqel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#197] opened 2021-06-03 17:13 UTC
Hi guys, I think this has been discussed before but I haven't seen a way to do it, so I'm trying to ask for help here.

I am trying to get a channel to stay connected in the IRC channel even when the person has disconnected from the stream, do you know of an easy way to do this? Thank you very much!

**Comment by RakSrinaNa** [comment] 2021-06-03 20:50
Duplicate of #115

**Comment by Yishaqel** [comment] 2021-06-17 10:07
I guess it will be to modify a line of a particular file to stay in a connected IRC channel, if anyone knows it would be useful for me. Thanks!

**Comment by RakSrinaNa** [comment] 2021-06-17 11:07
Why not just using an IRC client and you join the channels you want to join... There's plenty of solutions already available for that.

**Comment by NEVERZ0RED** [comment] 2021-06-17 15:46
> Why not just using an IRC client and you join the channels you want to join... There's plenty of solutions already available for that.

Good day, I am also very interested in how you can just stay in the broadcast chat, I will be very grateful for the information.

**Comment by Yishaqel** [comment] 2021-06-17 19:22
> Why not just using an IRC client and you join the channels you want to join... There's plenty of solutions already available for that.

I am currently using a laptop to get only points on two channels, it would be useful for me to have it all in 1 application.

**Comment by RakSrinaNa** [comment] 2021-06-17 19:26
It's not like having a python script and an irc client will consume a lot... 
I get the point of having an app that does everything. But it's better to have several apps that does each a good job at what they should do, rather than one that does a billion things but in a bad way.

An even if an IRC client isn't an option, you can always do a python script that stays on an IRC channel forever... In a few lines it should be ok and won't consume much resources.

**Closed** 2021-06-23 10:01 UTC
Labels: enhancement
