### ISSUE TITLE
25/04 23:21:36 - #1 - WebSocket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123) 25/04 23:21:57 - #2 - WebSocket closed 25/04 23:21:57 - #0 - WebSocket closed 25/04 23:21:57 - #1 - WebSocket closed 25/04 23:21:57 - #2 - Reconnecting to Twitch PubSub server in ~60 seconds

### ISSUE THREAD

**Issue by Emmes420** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#161] opened 2021-04-25 23:23 UTC
It spam that error after listed all t
![image](https://user-images.githubusercontent.com/48575205/116012996-b7906500-a5fb-11eb-90f6-62576250fb66.png)
he steamer

**Comment by RakSrinaNa** [comment] 2021-04-26 04:50
Duplicate of #159

**Closed** 2021-08-16 20:42 UTC
Labels: duplicate
