### ISSUE TITLE
The program worked for a day and then gives this error

### ISSUE THREAD

**Issue by YaZanuda111111** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#441] opened 2022-03-06 14:33 UTC
![image](https://user-images.githubusercontent.com/78689718/156927648-bc7dbf29-1521-492c-be63-d9539954a800.png)
The program worked for a day and then gives this error.

**Comment by YaZanuda111111** [comment] 2022-03-06 14:36
I can attach a log file if it is required to fix this error

**Comment by Tkd-Alex** [comment] 2022-03-06 14:40
This issue is a duplicated of another 3/4 issue, please search on GitHub

**Comment by Tkd-Alex** [comment] 2022-03-06 15:33
Duplicate of #398  https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/358 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/381 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/187 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/266

**Closed by Tkd-Alex** 2022-03-06 15:33 UTC
Labels: duplicate
